image: docker:20.10

services:
  - name: docker:20.10-dind
    entrypoint: ["dockerd-entrypoint.sh"]
    command: ["--insecure-registry", "registry.red-soft.biz:5000", "--registry-mirror", "http://registry-mirror.red-soft.biz:6000"]

variables:
    DOCKER_DRIVER: overlay2

build:
    tags:
      - docker
      - x86_64

    before_script:
      - docker login -u "$CI_REGISTRY_USER" -p "$CI_BUILD_TOKEN" "$DOCKER_ENV_CI_REGISTRY"

    script:
      - docker build -t "$CI_REGISTRY_IMAGE:latest" .
      - docker push "$CI_REGISTRY_IMAGE:latest"
